// Seed data for BD-NURSE Standalone & GitHub Pages runtime
window.WINDOW_DEPARTMENTS_DATA = [
  {
    "id": 1,
    "code": "NG_TH",
    "name": "Ngoại Tiêu hóa",
    "block": "Ngoại Tiêu hóa - Gan mật",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 2,
    "code": "PTDTT",
    "name": "Phẫu thuật Đại trực tràng",
    "block": "Ngoại Tiêu hóa - Gan mật",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 3,
    "code": "NG_GM",
    "name": "Ngoại Gan mật",
    "block": "Ngoại Tiêu hóa - Gan mật",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 4,
    "code": "UG",
    "name": "U Gan",
    "block": "Ngoại Tiêu hóa - Gan mật",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 5,
    "code": "NG_LNBC",
    "name": "Ngoại Lồng ngực – Bướu cổ",
    "block": "Ngoại Chuyên khoa",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 6,
    "code": "NG_THOP",
    "name": "Ngoại Tổng hợp",
    "block": "Ngoại Chuyên khoa",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 7,
    "code": "UB_TN",
    "name": "Ung bướu Tiết niệu",
    "block": "Khối Tiết niệu",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 8,
    "code": "NIEU_A",
    "name": "Niệu A",
    "block": "Khối Tiết niệu",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 9,
    "code": "NIEU_B",
    "name": "Niệu B",
    "block": "Khối Tiết niệu",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 10,
    "code": "ST_CS",
    "name": "Sỏi thận Chuyên sâu",
    "block": "Khối Tiết niệu",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 11,
    "code": "NIEU_C",
    "name": "Niệu C",
    "block": "Khối Tiết niệu",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 12,
    "code": "NIEU_DAO",
    "name": "Niệu đạo",
    "block": "Khối Tiết niệu",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 13,
    "code": "UB",
    "name": "Ung bướu",
    "block": "Khối Nội & Chuyên khoa",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 14,
    "code": "NOI_TH",
    "name": "Nội Tổng hợp",
    "block": "Khối Nội & Chuyên khoa",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 15,
    "code": "NAM_HOC",
    "name": "Nam học",
    "block": "Khối Tiết niệu",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 16,
    "code": "LOC_MAU",
    "name": "Lọc máu – Nội thận",
    "block": "Khối Nội & Chuyên khoa",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 17,
    "code": "NS_NIEU",
    "name": "Nội soi Niệu",
    "block": "Khối Can thiệp & Thủ thuật",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 18,
    "code": "HS_CC",
    "name": "Hồi sức Cấp cứu",
    "block": "Khối Hồi sức & Phẫu thuật",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 19,
    "code": "ICU",
    "name": "Hồi sức Tích cực và Chống độc",
    "block": "Khối Hồi sức & Phẫu thuật",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 20,
    "code": "GMHS_1",
    "name": "Gây mê Hồi sức I",
    "block": "Khối Hồi sức & Phẫu thuật",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 21,
    "code": "GMHS_2",
    "name": "Gây mê Hồi sức II",
    "block": "Khối Hồi sức & Phẫu thuật",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 22,
    "code": "NIEU_NU",
    "name": "Niệu nữ",
    "block": "Khối Tiết niệu",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 23,
    "code": "PT_TMM",
    "name": "Phẫu thuật Tim – Mạch máu",
    "block": "Ngoại Chuyên khoa",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 24,
    "code": "NS_TH",
    "name": "Nội soi Tiêu hóa",
    "block": "Khối Can thiệp & Thủ thuật",
    "default_head_nurse": "",
    "kap_preset_json": "[]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": []
  },
  {
    "id": 25,
    "code": "CDHA",
    "name": "Chẩn đoán hình ảnh",
    "block": "Khối Cận lâm sàng & Khám",
    "default_head_nurse": "",
    "kap_preset_json": "[\"chang_1\", \"muc_9\", \"muc_10\", \"muc_11\", \"muc_12\"]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": [
      "chang_1",
      "muc_9",
      "muc_10",
      "muc_11",
      "muc_12"
    ]
  },
  {
    "id": 26,
    "code": "XN",
    "name": "Xét nghiệm",
    "block": "Khối Cận lâm sàng & Khám",
    "default_head_nurse": "",
    "kap_preset_json": "[\"chang_1\", \"muc_9\", \"muc_10\", \"muc_11\", \"muc_12\"]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": [
      "chang_1",
      "muc_9",
      "muc_10",
      "muc_11",
      "muc_12"
    ]
  },
  {
    "id": 27,
    "code": "KHAM_BENH",
    "name": "Khám bệnh",
    "block": "Khối Cận lâm sàng & Khám",
    "default_head_nurse": "",
    "kap_preset_json": "[\"chang_1\", \"muc_9\", \"muc_11\", \"muc_12\"]",
    "created_at": "2026-10-02 07:33:03",
    "kap_preset": [
      "chang_1",
      "muc_9",
      "muc_11",
      "muc_12"
    ]
  }
];

window.WINDOW_CRITERIA_DATA = [
  {
    "id": 1,
    "chang": "Chặng I",
    "muc_stt": 1,
    "muc_ten": "Vệ sinh buồng bệnh & Tiện nghi an toàn",
    "noi_dung": "- Buồng bệnh thông thoáng, sạch sẽ, khô ráo, không mùi hôi; sàn nhà, quạt, tường không đọng bụi bẩn.",
    "diem": 1,
    "thu_tu": 1,
    "template_row": 4,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 2,
    "chang": "Chặng I",
    "muc_stt": 1,
    "muc_ten": "Vệ sinh buồng bệnh & Tiện nghi an toàn",
    "noi_dung": "- Tủ đầu giường gọn gàng; kéo thanh chắn giường an toàn.",
    "diem": 1,
    "thu_tu": 2,
    "template_row": 5,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 3,
    "chang": "Chặng I",
    "muc_stt": 1,
    "muc_ten": "Vệ sinh buồng bệnh & Tiện nghi an toàn",
    "noi_dung": "- Hệ thống oxy tường an toàn; bình làm ẩm sạch vô khuẩn, chứa nước cất đúng vạch, dán nhãn ngày bắt đầu, có treo bảng cấm lửa và cấm hút thuốc",
    "diem": 1,
    "thu_tu": 3,
    "template_row": 6,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 4,
    "chang": "Chặng I",
    "muc_stt": 2,
    "muc_ten": "Giao tiếp ứng xử AIDET & Tác phong ĐD",
    "noi_dung": "- Tác phong: Đeo thẻ đúng quy định, đội nón, mang khẩu trang, giày đúng quy định; đồng phục sạch sẽ.",
    "diem": 1,
    "thu_tu": 4,
    "template_row": 7,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 5,
    "chang": "Chặng I",
    "muc_stt": 2,
    "muc_ten": "Giao tiếp ứng xử AIDET & Tác phong ĐD",
    "noi_dung": "- Giao tiếp AIDET: Chào hỏi, tự giới thiệu tên/vai trò, giải thích rõ thời lượng và quy trình chăm sóc.",
    "diem": 1,
    "thu_tu": 5,
    "template_row": 8,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 6,
    "chang": "Chặng I",
    "muc_stt": 2,
    "muc_ten": "Giao tiếp ứng xử AIDET & Tác phong ĐD",
    "noi_dung": "- Lắng nghe ý kiến của NB/thân nhân; giải thích chu đáo dặn dò và nói lời Cảm ơn khi kết thúc can thiệp.",
    "diem": 1,
    "thu_tu": 6,
    "template_row": 9,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 7,
    "chang": "Chặng I",
    "muc_stt": 3,
    "muc_ten": "Thời gian có mặt kịp thời khi BN cần",
    "noi_dung": "- Phỏng vấn ngẫu nhiên 3 NB về thời gian có mặt của ĐD khi được gọi.",
    "diem": 1,
    "thu_tu": 7,
    "template_row": 10,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 8,
    "chang": "Chặng I",
    "muc_stt": 4,
    "muc_ten": "Nhận diện người bệnh & Đánh giá nguy cơ",
    "noi_dung": "- 100% NB đeo vòng định danh đúng thông tin.",
    "diem": 2,
    "thu_tu": 8,
    "template_row": 11,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 9,
    "chang": "Chặng I",
    "muc_stt": 4,
    "muc_ten": "Nhận diện người bệnh & Đánh giá nguy cơ",
    "noi_dung": "- 100% NB mặc đúng đồng phục bệnh viện; thực hiện đánh giá nguy cơ té ngã đúng thời điểm và có biện pháp phòng ngừa.",
    "diem": 2,
    "thu_tu": 9,
    "template_row": 12,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 10,
    "chang": "Chặng I",
    "muc_stt": 5,
    "muc_ten": "Nắm bệnh & Theo dõi Dấu hiệu sinh tồn (DHST)",
    "noi_dung": "- ĐD phụ trách buồng nắm vững chẩn đoán, diễn tiến bệnh, các can thiệp ưu tiên; nhận định bất thường báo BS kịp thời.",
    "diem": 2,
    "thu_tu": 10,
    "template_row": 13,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 11,
    "chang": "Chặng I",
    "muc_stt": 5,
    "muc_ten": "Nắm bệnh & Theo dõi Dấu hiệu sinh tồn (DHST)",
    "noi_dung": "- Đo và ghi nhận DHST đủ, đúng tần suất theo phân cấp chăm sóc (Cấp I, II, III) quy định tại TT 31/2021/TT-BYT.",
    "diem": 3,
    "thu_tu": 11,
    "template_row": 14,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 12,
    "chang": "Chặng I",
    "muc_stt": 6,
    "muc_ten": "Tư vấn nội quy, Dịch vụ & Công khai minh bạch",
    "noi_dung": "- Phổ biến nội quy buồng bệnh; giáo dục sức khỏe phù hợp với bệnh lý trong thời gian nằm viện và trước khi xuất viện.",
    "diem": 2,
    "thu_tu": 12,
    "template_row": 15,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 13,
    "chang": "Chặng I",
    "muc_stt": 6,
    "muc_ten": "Tư vấn nội quy, Dịch vụ & Công khai minh bạch",
    "noi_dung": "- Công khai vật tư y tế đầy đủ, chính xác, phù hợp với thực tế sử dụng và đúng quy định.",
    "diem": 2,
    "thu_tu": 13,
    "template_row": 16,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 14,
    "chang": "Chặng II",
    "muc_stt": 7,
    "muc_ten": "Chuẩn bị xe tiêm, xe thay băng & Dụng cụ",
    "noi_dung": "- Phân định riêng biệt xe tiêm và xe thay băng; xe sạch sẽ, phân 2 tầng sạch - bẩn riêng biệt.",
    "diem": 2,
    "thu_tu": 14,
    "template_row": 18,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 15,
    "chang": "Chặng II",
    "muc_stt": 7,
    "muc_ten": "Chuẩn bị xe tiêm, xe thay băng & Dụng cụ",
    "noi_dung": "- Thùng ngâm dụng cụ có nắp đậy, nhãn ghi rõ: tên hóa chất ngâm, nồng độ, ngày giờ pha và hạn dùng.",
    "diem": 2,
    "thu_tu": 15,
    "template_row": 19,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 16,
    "chang": "Chặng II",
    "muc_stt": 8,
    "muc_ten": "Tuân thủ Quy trình kỹ thuật (QTKT) & KSNK",
    "noi_dung": "- Tuân thủ đúng bảng kiểm QTKT chăm sóc. Thực hiện nghiêm ngặt 5 thời điểm vệ sinh tay theo chuẩn WHO.",
    "diem": 3,
    "thu_tu": 16,
    "template_row": 20,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 17,
    "chang": "Chặng II",
    "muc_stt": 8,
    "muc_ten": "Tuân thủ Quy trình kỹ thuật (QTKT) & KSNK",
    "noi_dung": "- Mang găng đúng chỉ định (tiêm, thay băng, đặt sonde...), giữ vô khuẩn tuyệt đối; an toàn vật sắc nhọn.",
    "diem": 3,
    "thu_tu": 17,
    "template_row": 21,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 18,
    "chang": "Chặng II",
    "muc_stt": 9,
    "muc_ten": "Quản lý kim luồn tĩnh mạch & Truyền dịch an toàn",
    "noi_dung": "- Kim luồn còn trong hạn (không quá 72-96h), cố định chắc, băng sạch; không sưng đỏ/viêm TM.",
    "diem": 3,
    "thu_tu": 18,
    "template_row": 22,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 19,
    "chang": "Chặng II",
    "muc_stt": 9,
    "muc_ten": "Quản lý kim luồn tĩnh mạch & Truyền dịch an toàn",
    "noi_dung": "- Chai dịch truyền dán nhãn đầy đủ: Họ tên NB, năm sinh, thuốc pha, liều lượng, tốc độ giọt, ngày thực hiện",
    "diem": 3,
    "thu_tu": 19,
    "template_row": 23,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 20,
    "chang": "Chặng II",
    "muc_stt": 10,
    "muc_ten": "Cấp phát thuốc uống an toàn",
    "noi_dung": "- Chia liều thuốc uống đúng cử, bao bì ghi rõ Họ tên NB, năm sinh, ngày thực hiện.",
    "diem": 1,
    "thu_tu": 20,
    "template_row": 24,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 21,
    "chang": "Chặng II",
    "muc_stt": 10,
    "muc_ten": "Cấp phát thuốc uống an toàn",
    "noi_dung": "- ĐD trực tiếp hướng dẫn, đối chiếu và chứng kiến NB uống thuốc tại giường; tư vấn tác dụng phụ cần theo dõi.",
    "diem": 2,
    "thu_tu": 21,
    "template_row": 25,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 22,
    "chang": "Chặng II",
    "muc_stt": 11,
    "muc_ten": "Chăm sóc và Quản lý các ống thông, sonde dẫn lưu",
    "noi_dung": "- Cố định đúng vị trí; túi chứa nước tiểu/dịch luôn treo thấp hơn vị trí dẫn lưu.",
    "diem": 2,
    "thu_tu": 22,
    "template_row": 26,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 23,
    "chang": "Chặng II",
    "muc_stt": 11,
    "muc_ten": "Chăm sóc và Quản lý các ống thông, sonde dẫn lưu",
    "noi_dung": "- Đánh giá, theo dõi và ghi chép số lượng, màu sắc, tính chất dịch xuất nhập; hướng dẫn NB vận động an toàn.",
    "diem": 2,
    "thu_tu": 23,
    "template_row": 27,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 24,
    "chang": "Chặng II",
    "muc_stt": 12,
    "muc_ten": "Quy trình An toàn Truyền máu tại giường",
    "noi_dung": "- Có chữ ký BS đọc kết quả định nhóm máu tại giường.",
    "diem": 3,
    "thu_tu": 24,
    "template_row": 28,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 25,
    "chang": "Chặng II",
    "muc_stt": 12,
    "muc_ten": "Quy trình An toàn Truyền máu tại giường",
    "noi_dung": "- Đo và ghi nhận DHST đủ 3 thời điểm chuẩn: Trước truyền, sau 15 phút, trong truyền và khi kết thúc truyền.",
    "diem": 4,
    "thu_tu": 25,
    "template_row": 29,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 26,
    "chang": "Chặng III",
    "muc_stt": 13,
    "muc_ten": "Quản lý Tủ thuốc trực & Tủ vật tư y tế",
    "noi_dung": "- Cơ số thuốc/VTYT thực tế khớp 100% danh mục phê duyệt; có sổ theo dõi mượn, bù, hoàn trả thuốc kịp thời.",
    "diem": 4,
    "thu_tu": 26,
    "template_row": 31,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 27,
    "chang": "Chặng III",
    "muc_stt": 13,
    "muc_ten": "Quản lý Tủ thuốc trực & Tủ vật tư y tế",
    "noi_dung": "- Sắp xếp gọn gàng; dán nhãn cảnh báo Thuốc nguy cơ & Thuốc nhìn/đọc giống nhau (LASA).",
    "diem": 1,
    "thu_tu": 27,
    "template_row": 32,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 28,
    "chang": "Chặng III",
    "muc_stt": 13,
    "muc_ten": "Quản lý Tủ thuốc trực & Tủ vật tư y tế",
    "noi_dung": "- Có nhiệt ẩm kế, theo dõi và ghi biểu đồ nhiệt độ phòng và tủ lạnh bảo quản thuốc (2 - 8°C) hàng ngày.",
    "diem": 1,
    "thu_tu": 28,
    "template_row": 33,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 29,
    "chang": "Chặng III",
    "muc_stt": 14,
    "muc_ten": "Vali Cấp cứu & Hộp thuốc Chống sốc phản vệ",
    "noi_dung": "- Đầy đủ 100% cơ số thuốc cấp cứu (Adrenalin...) và TTB theo TT 51/2017/TT-BYT; thuốc và vật tư còn hạn, sẵn sàng 24/24.",
    "diem": 2,
    "thu_tu": 29,
    "template_row": 34,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 30,
    "chang": "Chặng III",
    "muc_stt": 14,
    "muc_ten": "Vali Cấp cứu & Hộp thuốc Chống sốc phản vệ",
    "noi_dung": "- Phác đồ xử trí phản vệ và sơ đồ vị trí thuốc, vật tư dán trên hộp rõ ràng, dễ thấy; kiểm tra niêm phong định kỳ.",
    "diem": 2,
    "thu_tu": 30,
    "template_row": 35,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 31,
    "chang": "Chặng III",
    "muc_stt": 15,
    "muc_ten": "Dụng cụ vô khuẩn & Dung dịch sát khuẩn",
    "noi_dung": "- Gói dụng cụ vô khuẩn còn nguyên niêm phong, không rách ướt; còn trong hạn.",
    "diem": 2,
    "thu_tu": 31,
    "template_row": 36,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 32,
    "chang": "Chặng III",
    "muc_stt": 15,
    "muc_ten": "Dụng cụ vô khuẩn & Dung dịch sát khuẩn",
    "noi_dung": "- Dung dịch sát khuẩn (Cồn, Povidine...) ghi rõ ngày mở nắp và hạn dùng sau mở; không sử dụng chai quá hạn.",
    "diem": 1,
    "thu_tu": 32,
    "template_row": 37,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 33,
    "chang": "Chặng III",
    "muc_stt": 16,
    "muc_ten": "Phân loại và Quản lý chất thải (TT 20/2021/TT-BYT)",
    "noi_dung": "- Thùng rác đạp chân có nắp đậy, nhãn phân loại rõ ràng; thành và đáy thùng sạch sẽ, lót bao đúng màu quy định.",
    "diem": 2,
    "thu_tu": 33,
    "template_row": 38,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 34,
    "chang": "Chặng III",
    "muc_stt": 16,
    "muc_ten": "Phân loại và Quản lý chất thải (TT 20/2021/TT-BYT)",
    "noi_dung": "- Phân loại rác y tế lây nhiễm, rác sinh hoạt, vật sắc nhọn đúng 100% quy chuẩn; không vứt lẫn lộn rác.",
    "diem": 2,
    "thu_tu": 34,
    "template_row": 39,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 35,
    "chang": "Chặng III",
    "muc_stt": 16,
    "muc_ten": "Phân loại và Quản lý chất thải (TT 20/2021/TT-BYT)",
    "noi_dung": "- Thùng rác không chứa vượt quá 3/4 thể tích; thu gom, buộc kín và vận chuyển rác đúng khung giờ quy định.",
    "diem": 1,
    "thu_tu": 35,
    "template_row": 40,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 36,
    "chang": "Chặng III",
    "muc_stt": 17,
    "muc_ten": "Hệ thống oxy",
    "noi_dung": "- Hệ thống oxy tường an toàn; bình làm ẩm sạch vô khuẩn, chứa nước cất đúng vạch, dán nhãn ngày bắt đầu, có treo bảng cấm lửa và cấm hút thuốc, có nắp bảo vệ khi không sử dụng.",
    "diem": 1,
    "thu_tu": 36,
    "template_row": 41,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 37,
    "chang": "Chặng III",
    "muc_stt": 17,
    "muc_ten": "Hệ thống oxy",
    "noi_dung": "- Hệ thống oxy trung chuyển có nắp bảo vệ khi không sử dụng, có treo bảng cấm lửa và cấm hút thuốc, sẵn sàng 24/24.",
    "diem": 1,
    "thu_tu": 37,
    "template_row": 42,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 38,
    "chang": "Chặng IV",
    "muc_stt": 18,
    "muc_ten": "Phiếu theo dõi và chăm sóc người bệnh",
    "noi_dung": "Xuất Phiếu theo dõi và chăm sóc người bệnh, ký số hằng ngày theo quy định.",
    "diem": 2,
    "thu_tu": 38,
    "template_row": 44,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 39,
    "chang": "Chặng IV",
    "muc_stt": 18,
    "muc_ten": "Phiếu theo dõi và chăm sóc người bệnh",
    "noi_dung": "Ghi chép đầy đủ, chính xác bệnh lý kèm theo và tiền sử dị ứng.",
    "diem": 1,
    "thu_tu": 39,
    "template_row": 45,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 40,
    "chang": "Chặng IV",
    "muc_stt": 18,
    "muc_ten": "Phiếu theo dõi và chăm sóc người bệnh",
    "noi_dung": "Phân cấp chăm sóc phù hợp với tình trạng NB và y lệnh BS",
    "diem": 1,
    "thu_tu": 40,
    "template_row": 46,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 41,
    "chang": "Chặng IV",
    "muc_stt": 18,
    "muc_ten": "Phiếu theo dõi và chăm sóc người bệnh",
    "noi_dung": "Tính điểm MEWS chính xác và tái đánh giá đúng thời điểm.",
    "diem": 1,
    "thu_tu": 41,
    "template_row": 47,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 42,
    "chang": "Chặng IV",
    "muc_stt": 18,
    "muc_ten": "Phiếu theo dõi và chăm sóc người bệnh",
    "noi_dung": "Nhận định đầy đủ và phù hợp các nội dung trong khung giờ buổi sáng và khi tiếp nhận NB  từ khoa khác.",
    "diem": 1,
    "thu_tu": 42,
    "template_row": 48,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 43,
    "chang": "Chặng IV",
    "muc_stt": 18,
    "muc_ten": "Phiếu theo dõi và chăm sóc người bệnh",
    "noi_dung": "Nhận định và kế hoạch chăm sóc phải phù hợp, cập nhật kịp thời khi tình trạng người bệnh thay đổi.",
    "diem": 1,
    "thu_tu": 43,
    "template_row": 49,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 44,
    "chang": "Chặng IV",
    "muc_stt": 18,
    "muc_ten": "Phiếu theo dõi và chăm sóc người bệnh",
    "noi_dung": "Ghi nhận đầy đủ, chính xác thời gian đặt và rút kim luồn, ống thông theo quy định.",
    "diem": 1,
    "thu_tu": 44,
    "template_row": 50,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 45,
    "chang": "Chặng IV",
    "muc_stt": 19,
    "muc_ten": "Thực hiện kế hoạch chăm sóc",
    "noi_dung": "Chẩn đoán điều dưỡng được thực hiện đúng quy định và đầy đủ các vấn đề nhận định",
    "diem": 1,
    "thu_tu": 45,
    "template_row": 51,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 46,
    "chang": "Chặng IV",
    "muc_stt": 19,
    "muc_ten": "Thực hiện kế hoạch chăm sóc",
    "noi_dung": "Xác định mục tiêu chăm sóc phù hợp với chẩn đoán điều dưỡng",
    "diem": 1,
    "thu_tu": 46,
    "template_row": 52,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 47,
    "chang": "Chặng IV",
    "muc_stt": 19,
    "muc_ten": "Thực hiện kế hoạch chăm sóc",
    "noi_dung": "Thực hiện đầy đủ các can thiệp điều dưỡng, phù hợp với chuyên môn và y lệnh của bác sĩ; lồng ghép giáo dục sức khỏe phù hợp.",
    "diem": 2,
    "thu_tu": 47,
    "template_row": 53,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 48,
    "chang": "Chặng IV",
    "muc_stt": 19,
    "muc_ten": "Thực hiện kế hoạch chăm sóc",
    "noi_dung": "Lượng giá kết quả chăm sóc đầy đủ, kịp thời theo mục tiêu đã xác định.",
    "diem": 1,
    "thu_tu": 48,
    "template_row": 54,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 49,
    "chang": "Chặng IV",
    "muc_stt": 19,
    "muc_ten": "Thực hiện kế hoạch chăm sóc",
    "noi_dung": "Nhập riêng từng vấn đề chăm sóc; các nội dung liên quan phải thẳng hàng, không lệch dòng hoặc nhập gộp.",
    "diem": 1,
    "thu_tu": 49,
    "template_row": 55,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 50,
    "chang": "Chặng IV",
    "muc_stt": 20,
    "muc_ten": "Thực hiện y lệnh và bàn giao người bệnh",
    "noi_dung": "- Thực hiện truyền dịch đầy đủ, đúng quy định.",
    "diem": 1,
    "thu_tu": 50,
    "template_row": 56,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 51,
    "chang": "Chặng IV",
    "muc_stt": 20,
    "muc_ten": "Thực hiện y lệnh và bàn giao người bệnh",
    "noi_dung": "- Thực hiện đầy đủ, đúng y lệnh các thuốc, cận lâm sàng và dịch vụ kỹ thuật",
    "diem": 2,
    "thu_tu": 51,
    "template_row": 57,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 52,
    "chang": "Chặng IV",
    "muc_stt": 20,
    "muc_ten": "Thực hiện y lệnh và bàn giao người bệnh",
    "noi_dung": "- Có chữ ký xác nhận hằng ngày của người bệnh hoặc thân nhân theo quy định",
    "diem": 1,
    "thu_tu": 52,
    "template_row": 58,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 53,
    "chang": "Chặng IV",
    "muc_stt": 20,
    "muc_ten": "Thực hiện y lệnh và bàn giao người bệnh",
    "noi_dung": "- Bàn giao người bệnh giữa các ca, các tua trực và các khoa đầy đủ, đúng quy định.",
    "diem": 1,
    "thu_tu": 53,
    "template_row": 59,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 54,
    "chang": "Chặng IV",
    "muc_stt": 21,
    "muc_ten": "Đánh giá và phòng ngừa té ngã",
    "noi_dung": "- Đánh giá đúng thời điểm quy định",
    "diem": 1,
    "thu_tu": 54,
    "template_row": 60,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 55,
    "chang": "Chặng IV",
    "muc_stt": 21,
    "muc_ten": "Đánh giá và phòng ngừa té ngã",
    "noi_dung": "- Chấm điểm đúng các tiêu chí",
    "diem": 1,
    "thu_tu": 55,
    "template_row": 61,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 56,
    "chang": "Chặng IV",
    "muc_stt": 21,
    "muc_ten": "Đánh giá và phòng ngừa té ngã",
    "noi_dung": "- Ghi nhận các biện pháp phòng ngừa té ngã trên Phiếu theo dõi và chăm sóc đối với NB có nguy cơ té ngã cao.",
    "diem": 1,
    "thu_tu": 56,
    "template_row": 62,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 57,
    "chang": "Chặng IV",
    "muc_stt": 21,
    "muc_ten": "Đánh giá và phòng ngừa té ngã",
    "noi_dung": "- Thực hiện đánh giá lại hằng ngày đối với người bệnh có nguy cơ té ngã cao cho đến khi mức nguy cơ giảm.",
    "diem": 1,
    "thu_tu": 57,
    "template_row": 63,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 58,
    "chang": "Chặng IV",
    "muc_stt": 22,
    "muc_ten": "Biểu mẫu khác và quản lý hồ sơ",
    "noi_dung": "- “Phiếu tư vấn thực hiện quy trình kỹ thuật chăm sóc, Phiếu bàn giao NB chuyển khoa, Bảng kiểm soát người bệnh trước khi lên phòng mổ” phải được thực hiện đầy đủ, chính xác và có đủ chữ ký theo quy định.",
    "diem": 1,
    "thu_tu": 58,
    "template_row": 64,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 59,
    "chang": "Chặng IV",
    "muc_stt": 22,
    "muc_ten": "Biểu mẫu khác và quản lý hồ sơ",
    "noi_dung": "- Hồ sơ ra viện hoàn tất 100% biểu mẫu, in bảng kê BV02 đầy đủ chữ ký trước khi chuyển phòng KHTH.",
    "diem": 1,
    "thu_tu": 59,
    "template_row": 65,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 60,
    "chang": "Chặng V",
    "muc_stt": 23,
    "muc_ten": "Sổ sách bàn giao chuyên môn",
    "noi_dung": "- Giao ban, báo cáo trực, sổ đi buồng",
    "diem": 1,
    "thu_tu": 60,
    "template_row": 67,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 61,
    "chang": "Chặng V",
    "muc_stt": 23,
    "muc_ten": "Sổ sách bàn giao chuyên môn",
    "noi_dung": "- Bàn giao thuốc/VTYT tủ trực, bàn giao máy móc, dụng cụ cố định",
    "diem": 1,
    "thu_tu": 61,
    "template_row": 68,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 62,
    "chang": "Chặng V",
    "muc_stt": 23,
    "muc_ten": "Sổ sách bàn giao chuyên môn",
    "noi_dung": "- Bàn giao đồ vải",
    "diem": 1,
    "thu_tu": 62,
    "template_row": 69,
    "created_at": "2026-10-02 07:33:03"
  },
  {
    "id": 63,
    "chang": "Chặng V",
    "muc_stt": 23,
    "muc_ten": "Sổ sách bàn giao chuyên môn",
    "noi_dung": "- Ghi chép rõ ràng, khớp số liệu.đủ 2 chữ ký giao - nhận.",
    "diem": 2,
    "thu_tu": 63,
    "template_row": 70,
    "created_at": "2026-10-02 07:33:03"
  }
];
