services:
  - type: web
    name: bd-nurse
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python scripts/start_cloud.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
    autoDeploy: true
